### ISSUE TITLE
Initial content

### ISSUE THREAD

**Issue by docktermj** [Senzing/mapper-base#1]

**Comment by jbutcher21** [comment]
https://github.com/Senzing/mapper-base/pull/2
https://github.com/Senzing/mapper-base/pull/3
https://github.com/Senzing/mapper-base/pull/4
https://github.com/Senzing/mapper-base/pull/5

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/mapper-base/pull/6
2. https://github.com/Senzing/mapper-base/pull/7
